<a href="https://colab.research.google.com/github/Atherizz/ML_2026/blob/main/JS02/praktikum_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [ ]:
dpath = 'https://raw.githubusercontent.com/Atherizz/ML_2026/main/JS02/data/Titanic-Dataset-fixed.csv'
df = pd.read_csv(dpath)
df.head()

HTTPError: HTTP Error 404: Not Found

In [ ]:
df = df[['Survived', 'Pclass', 'Age', 'Sex', 'Cabin']]
df.head()

   Survived  Pclass   Age     Sex Cabin
0         0       3  22.0    male  DECK
1         1       1  38.0  female   C85
2         1       3  26.0  female  DECK
3         1       1  35.0  female  C123
4         0       3  35.0    male  DECK

In [ ]:
from sklearn.preprocessing import LabelEncoder,StandardScaler

le = LabelEncoder() # membuat objek dari LabelEncoder
df['Sex'] = le.fit_transform(df['Sex']) # proses encoding
df['Cabin'] = le.fit_transform(df['Cabin']) # proses encoding

In [ ]:
df.head()

   Survived  Pclass   Age  Sex  Cabin
0         0       3  22.0    1    115
1         1       1  38.0    0     81
2         1       3  26.0    0    115
3         1       1  35.0    0     55
4         0       3  35.0    1    115

In [ ]:
std = StandardScaler()
df['Age'] = std.fit_transform(df[['Age']])

In [ ]:

df.head()

   Survived  Pclass       Age  Sex  Cabin
0         0       3 -0.592481    1    115
1         1       1  0.638789    0     81
2         1       3 -0.284663    0    115
3         1       1  0.407926    0     55
4         0       3  0.407926    1    115